//! Stable string tags for [`crate::shared::RendererCommand`] variants (diagnostics, counters).
//!
//! Kept exhaustive so adding a new IPC variant forces an update here and in the host generator.

use crate::shared::RendererCommand;

/// Returns a stable tag for logging and unhandled-command counters when the enum grows.
pub(super) fn renderer_command_variant_tag(cmd: &RendererCommand) -> &'static str {
    match cmd {
        RendererCommand::RendererInitData(_) => "RendererInitData",
        RendererCommand::RendererInitResult(_) => "RendererInitResult",
        RendererCommand::RendererInitProgressUpdate(_) => "RendererInitProgressUpdate",
        RendererCommand::RendererInitFinalizeData(_) => "RendererInitFinalizeData",
        RendererCommand::RendererEngineReady(_) => "RendererEngineReady",
        RendererCommand::RendererShutdownRequest(_) => "RendererShutdownRequest",
        RendererCommand::RendererShutdown(_) => "RendererShutdown",
        RendererCommand::KeepAlive(_) => "KeepAlive",
        RendererCommand::RendererParentWindow(_) => "RendererParentWindow",
        RendererCommand::FreeSharedMemoryView(_) => "FreeSharedMemoryView",
        RendererCommand::SetWindowIcon(_) => "SetWindowIcon",
        RendererCommand::SetWindowIconResult(_) => "SetWindowIconResult",
        RendererCommand::SetTaskbarProgress(_) => "SetTaskbarProgress",
        RendererCommand::FrameStartData(_) => "FrameStartData",
        RendererCommand::FrameSubmitData(_) => "FrameSubmitData",
        RendererCommand::PostProcessingConfig(_) => "PostProcessingConfig",
        RendererCommand::QualityConfig(_) => "QualityConfig",
        RendererCommand::ResolutionConfig(_) => "ResolutionConfig",
        RendererCommand::DesktopConfig(_) => "DesktopConfig",
        RendererCommand::GaussianSplatConfig(_) => "GaussianSplatConfig",
        RendererCommand::RenderDecouplingConfig(_) => "RenderDecouplingConfig",
        RendererCommand::MeshUploadData(_) => "MeshUploadData",
        RendererCommand::MeshUnload(_) => "MeshUnload",
        RendererCommand::MeshUploadResult(_) => "MeshUploadResult",
        RendererCommand::ShaderUpload(_) => "ShaderUpload",
        RendererCommand::ShaderUnload(_) => "ShaderUnload",
        RendererCommand::ShaderUploadResult(_) => "ShaderUploadResult",
        RendererCommand::MaterialPropertyIdRequest(_) => "MaterialPropertyIdRequest",
        RendererCommand::MaterialPropertyIdResult(_) => "MaterialPropertyIdResult",
        RendererCommand::MaterialsUpdateBatch(_) => "MaterialsUpdateBatch",
        RendererCommand::MaterialsUpdateBatchResult(_) => "MaterialsUpdateBatchResult",
        RendererCommand::UnloadMaterial(_) => "UnloadMaterial",
        RendererCommand::UnloadMaterialPropertyBlock(_) => "UnloadMaterialPropertyBlock",
        RendererCommand::SetTexture2DFormat(_) => "SetTexture2DFormat",
        RendererCommand::SetTexture2DProperties(_) => "SetTexture2DProperties",
        RendererCommand::SetTexture2DData(_) => "SetTexture2DData",
        RendererCommand::SetTexture2DResult(_) => "SetTexture2DResult",
        RendererCommand::UnloadTexture2D(_) => "UnloadTexture2D",
        RendererCommand::SetTexture3DFormat(_) => "SetTexture3DFormat",
        RendererCommand::SetTexture3DProperties(_) => "SetTexture3DProperties",
        RendererCommand::SetTexture3DData(_) => "SetTexture3DData",
        RendererCommand::SetTexture3DResult(_) => "SetTexture3DResult",
        RendererCommand::UnloadTexture3D(_) => "UnloadTexture3D",
        RendererCommand::SetCubemapFormat(_) => "SetCubemapFormat",
        RendererCommand::SetCubemapProperties(_) => "SetCubemapProperties",
        RendererCommand::SetCubemapData(_) => "SetCubemapData",
        RendererCommand::SetCubemapResult(_) => "SetCubemapResult",
        RendererCommand::UnloadCubemap(_) => "UnloadCubemap",
        RendererCommand::SetRenderTextureFormat(_) => "SetRenderTextureFormat",
        RendererCommand::RenderTextureResult(_) => "RenderTextureResult",
        RendererCommand::UnloadRenderTexture(_) => "UnloadRenderTexture",
        RendererCommand::SetDesktopTextureProperties(_) => "SetDesktopTextureProperties",
        RendererCommand::DesktopTexturePropertiesUpdate(_) => "DesktopTexturePropertiesUpdate",
        RendererCommand::UnloadDesktopTexture(_) => "UnloadDesktopTexture",
        RendererCommand::PointRenderBufferUpload(_) => "PointRenderBufferUpload",
        RendererCommand::PointRenderBufferConsumed(_) => "PointRenderBufferConsumed",
        RendererCommand::PointRenderBufferUnload(_) => "PointRenderBufferUnload",
        RendererCommand::TrailRenderBufferUpload(_) => "TrailRenderBufferUpload",
        RendererCommand::TrailRenderBufferConsumed(_) => "TrailRenderBufferConsumed",
        RendererCommand::TrailRenderBufferUnload(_) => "TrailRenderBufferUnload",
        RendererCommand::GaussianSplatUploadRaw(_) => "GaussianSplatUploadRaw",
        RendererCommand::GaussianSplatUploadEncoded(_) => "GaussianSplatUploadEncoded",
        RendererCommand::GaussianSplatResult(_) => "GaussianSplatResult",
        RendererCommand::UnloadGaussianSplat(_) => "UnloadGaussianSplat",
        RendererCommand::LightsBufferRendererSubmission(_) => "LightsBufferRendererSubmission",
        RendererCommand::LightsBufferRendererConsumed(_) => "LightsBufferRendererConsumed",
        RendererCommand::ReflectionProbeRenderResult(_) => "ReflectionProbeRenderResult",
        RendererCommand::VideoTextureLoad(_) => "VideoTextureLoad",
        RendererCommand::VideoTextureUpdate(_) => "VideoTextureUpdate",
        RendererCommand::VideoTextureReady(_) => "VideoTextureReady",
        RendererCommand::VideoTextureChanged(_) => "VideoTextureChanged",
        RendererCommand::VideoTextureProperties(_) => "VideoTextureProperties",
        RendererCommand::VideoTextureStartAudioTrack(_) => "VideoTextureStartAudioTrack",
        RendererCommand::UnloadVideoTexture(_) => "UnloadVideoTexture",
    }
}
