//! Generated cubemap environments for analytic skybox materials.

use std::borrow::Cow;
use std::collections::hash_map::DefaultHasher;
use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::sync::Arc;

use bytemuck::{Pod, Zeroable};
use thiserror::Error;
use wgpu::util::DeviceExt;

use crate::assets::material::MaterialPropertyLookupIds;
use crate::backend::frame_gpu::{
    SkyboxSpecularEnvironmentSource, SkyboxSpecularGeneratedCubemapSource,
};
use crate::backend::skybox_params::{
    gradient_sky_params, procedural_sky_params, DEFAULT_GENERATED_SKYBOX_FACE_SIZE,
};
use crate::embedded_shaders;
use crate::gpu::{GpuContext, GpuLimits};
use crate::resources::CubemapSamplerState;
use crate::scene::SceneCoordinator;

use super::{GpuJobResources, GpuSubmitJobTracker, SubmittedGpuJob};

/// Maximum generated skybox bake jobs allowed in flight at once.
const MAX_IN_FLIGHT_SKYBOX_BAKES: usize = 2;
/// Number of renderer ticks before a skybox bake completion callback is treated as lost.
const MAX_PENDING_SKYBOX_BAKE_AGE_FRAMES: u32 = 120;
/// Generated cubemap format used by analytic skybox bake compute.
const GENERATED_SKYBOX_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba16Float;
/// Compute workgroup edge used by skybox bake and mip generation shaders.
const SKYBOX_WORKGROUP_EDGE: u32 = 8;

/// Uniform payload for one generated cubemap mip downsample pass.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
struct DownsampleParams {
    /// Destination mip face edge.
    dst_size: u32,
    /// Reserved alignment slot.
    _pad0: u32,
    /// Reserved alignment slot.
    _pad1: u32,
    /// Reserved alignment slot.
    _pad2: u32,
}

/// Errors returned while preparing skybox bake GPU work.
#[derive(Debug, Error)]
enum SkyboxEnvironmentBakeError {
    /// Embedded WGSL source was not available.
    #[error("embedded shader {0} not found")]
    MissingShader(&'static str),
}

/// Identity for one generated skybox cubemap.
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
struct GeneratedSkyboxKey {
    /// Active skybox material asset id.
    material_asset_id: i32,
    /// Material property generation used to invalidate baked results.
    material_generation: u64,
    /// Shader route hash so material shader changes invalidate baked results.
    route_hash: u64,
    /// Generated cubemap mip0 face size.
    face_size: u32,
}

impl GeneratedSkyboxKey {
    /// Returns a stable renderer-local hash for frame-global binding keys.
    fn source_hash(&self) -> u64 {
        let mut hasher = DefaultHasher::new();
        self.hash(&mut hasher);
        hasher.finish()
    }
}

/// Resolved active skybox bake request.
struct SkyboxBakeRequest {
    /// Generated cubemap identity.
    key: GeneratedSkyboxKey,
    /// Packed material evaluator parameters for the bake shader.
    params: crate::backend::skybox_params::SkyboxEvaluatorParams,
}

/// Completed generated skybox cubemap ready for frame-global specular binding.
struct GeneratedSkyboxEnvironment {
    /// Texture backing the generated cube view.
    _texture: Arc<wgpu::Texture>,
    /// Full mip-chain cube view.
    view: Arc<wgpu::TextureView>,
    /// Sampler fields used when building the frame-global sampler.
    sampler: CubemapSamplerState,
    /// Mip count generated by the bake job.
    mip_levels: u32,
}

impl GeneratedSkyboxEnvironment {
    /// Converts the generated cubemap into a frame-global specular source.
    fn to_specular_source(&self, key: &GeneratedSkyboxKey) -> SkyboxSpecularEnvironmentSource {
        SkyboxSpecularEnvironmentSource::GeneratedCubemap(SkyboxSpecularGeneratedCubemapSource {
            key_hash: key.source_hash(),
            view: self.view.clone(),
            sampler: self.sampler.clone(),
            mip_levels_resident: self.mip_levels,
            storage_v_inverted: false,
        })
    }
}

/// Generated cubemap plus transient resources retained until submit completion.
struct PendingGeneratedSkybox {
    /// Completed environment that becomes visible after submit completion.
    environment: GeneratedSkyboxEnvironment,
    /// Uniform and transient buffers retained until the queued commands complete.
    _buffers: Vec<wgpu::Buffer>,
    /// Bind groups retained until the queued commands complete.
    _bind_groups: Vec<wgpu::BindGroup>,
    /// One-mip texture views retained until the queued commands complete.
    _texture_views: Vec<wgpu::TextureView>,
    /// Sampler retained until the queued commands complete.
    _sampler: wgpu::Sampler,
}

/// Lazily-created compute pipeline and bind-group layout.
struct ComputePipelineWithLayout {
    /// Compute pipeline.
    pipeline: wgpu::ComputePipeline,
    /// Bind-group layout for this pipeline.
    layout: wgpu::BindGroupLayout,
}

/// Owns generated skybox environment bakes and completed cubemap cache entries.
pub(crate) struct SkyboxEnvironmentCache {
    /// Submit-completion tracker for in-flight bake command buffers.
    jobs: GpuSubmitJobTracker<GeneratedSkyboxKey>,
    /// In-flight generated cubemaps retained until their submit callback fires.
    pending: HashMap<GeneratedSkyboxKey, PendingGeneratedSkybox>,
    /// Completed generated cubemaps keyed by active material identity.
    completed: HashMap<GeneratedSkyboxKey, GeneratedSkyboxEnvironment>,
    /// Lazily-created procedural/gradient bake pipeline.
    bake_pipeline: Option<ComputePipelineWithLayout>,
    /// Lazily-created mip downsample pipeline.
    downsample_pipeline: Option<ComputePipelineWithLayout>,
}

impl Default for SkyboxEnvironmentCache {
    fn default() -> Self {
        Self::new()
    }
}

impl SkyboxEnvironmentCache {
    /// Creates an empty generated skybox environment cache.
    pub(crate) fn new() -> Self {
        Self {
            jobs: GpuSubmitJobTracker::new(MAX_PENDING_SKYBOX_BAKE_AGE_FRAMES),
            pending: HashMap::new(),
            completed: HashMap::new(),
            bake_pipeline: None,
            downsample_pipeline: None,
        }
    }

    /// Advances bake completions and schedules the active analytic skybox if needed.
    pub(crate) fn maintain(
        &mut self,
        gpu: &GpuContext,
        scene: &SceneCoordinator,
        materials: &crate::backend::MaterialSystem,
    ) {
        profiling::scope!("skybox_environment::maintain");
        let _ = gpu.device().poll(wgpu::PollType::Poll);
        self.drain_completed_jobs();
        let active = resolve_active_bake_request(scene, materials, gpu.limits());
        self.prune_completed(active.as_ref().map(|request| &request.key));
        let Some(request) = active else {
            return;
        };
        if self.completed.contains_key(&request.key)
            || self.pending.contains_key(&request.key)
            || self.jobs.contains_key(&request.key)
            || self.jobs.len() >= MAX_IN_FLIGHT_SKYBOX_BAKES
        {
            return;
        }
        match self.schedule_bake(gpu, request) {
            Ok(()) => {}
            Err(e) => logger::warn!("skybox_environment: generated cubemap bake failed: {e}"),
        }
    }

    /// Resolves the active generated skybox cubemap, if a completed one is available.
    pub(crate) fn active_specular_source(
        &self,
        scene: &SceneCoordinator,
        materials: &crate::backend::MaterialSystem,
        limits: &GpuLimits,
    ) -> Option<SkyboxSpecularEnvironmentSource> {
        let request = resolve_active_bake_request(scene, materials, limits)?;
        self.completed
            .get(&request.key)
            .map(|environment| environment.to_specular_source(&request.key))
    }

    /// Moves submit-completed bake results into the completed cache.
    fn drain_completed_jobs(&mut self) {
        let outcomes = self.jobs.maintain();
        for key in outcomes.completed {
            if let Some(pending) = self.pending.remove(&key) {
                self.completed.insert(key, pending.environment);
            }
        }
        for key in outcomes.failed {
            self.pending.remove(&key);
            logger::warn!("skybox_environment: generated cubemap bake expired before completion");
        }
    }

    /// Drops completed entries that cannot be used by the current active skybox.
    fn prune_completed(&mut self, active: Option<&GeneratedSkyboxKey>) {
        self.completed
            .retain(|key, _| active.is_some_and(|active_key| active_key == key));
    }

    /// Encodes and submits one generated cubemap bake.
    fn schedule_bake(
        &mut self,
        gpu: &GpuContext,
        request: SkyboxBakeRequest,
    ) -> Result<(), SkyboxEnvironmentBakeError> {
        let _ = ensure_pipeline(
            &mut self.bake_pipeline,
            gpu.device(),
            "skybox_bake_params",
            &bake_layout_entries(),
        )?;
        let _ = ensure_pipeline(
            &mut self.downsample_pipeline,
            gpu.device(),
            "skybox_downsample_cubemap",
            &downsample_layout_entries(),
        )?;
        let bake_pipeline =
            self.bake_pipeline
                .as_ref()
                .ok_or(SkyboxEnvironmentBakeError::MissingShader(
                    "skybox_bake_params",
                ))?;
        let downsample_pipeline =
            self.downsample_pipeline
                .as_ref()
                .ok_or(SkyboxEnvironmentBakeError::MissingShader(
                    "skybox_downsample_cubemap",
                ))?;
        let face_size = request.key.face_size;
        let mip_levels = mip_levels_for_edge(face_size);
        let texture = Arc::new(gpu.device().create_texture(&wgpu::TextureDescriptor {
            label: Some("generated_skybox_environment_cube"),
            size: wgpu::Extent3d {
                width: face_size,
                height: face_size,
                depth_or_array_layers: 6,
            },
            mip_level_count: mip_levels,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: GENERATED_SKYBOX_FORMAT,
            usage: wgpu::TextureUsages::TEXTURE_BINDING
                | wgpu::TextureUsages::STORAGE_BINDING
                | wgpu::TextureUsages::COPY_SRC,
            view_formats: &[],
        }));
        let full_view = Arc::new(texture.create_view(&wgpu::TextureViewDescriptor {
            label: Some("generated_skybox_environment_cube_view"),
            format: Some(GENERATED_SKYBOX_FORMAT),
            dimension: Some(wgpu::TextureViewDimension::Cube),
            usage: Some(wgpu::TextureUsages::TEXTURE_BINDING),
            aspect: wgpu::TextureAspect::All,
            base_mip_level: 0,
            mip_level_count: Some(mip_levels),
            base_array_layer: 0,
            array_layer_count: Some(6),
        }));
        let sampler = gpu.device().create_sampler(&wgpu::SamplerDescriptor {
            label: Some("generated_skybox_mip_sampler"),
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            mipmap_filter: wgpu::MipmapFilterMode::Linear,
            ..Default::default()
        });
        let mut buffers = Vec::new();
        let mut bind_groups = Vec::new();
        let mut texture_views = Vec::new();
        let mut encoder = gpu
            .device()
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("generated skybox bake encoder"),
            });
        let params_buffer = gpu
            .device()
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("generated skybox params"),
                contents: bytemuck::bytes_of(&request.params),
                usage: wgpu::BufferUsages::UNIFORM,
            });
        let mip0_storage = create_mip_storage_view(texture.as_ref(), 0);
        let bake_bind_group = gpu.device().create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("generated skybox bake bind group"),
            layout: &bake_pipeline.layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: params_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&mip0_storage),
                },
            ],
        });
        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("generated skybox bake"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&bake_pipeline.pipeline);
            pass.set_bind_group(0, &bake_bind_group, &[]);
            pass.dispatch_workgroups(dispatch_groups(face_size), dispatch_groups(face_size), 6);
        }
        buffers.push(params_buffer);
        bind_groups.push(bake_bind_group);
        texture_views.push(mip0_storage);
        encode_downsample_mips(
            gpu.device(),
            &mut encoder,
            downsample_pipeline,
            texture.as_ref(),
            &sampler,
            mip_levels,
            &mut buffers,
            &mut bind_groups,
            &mut texture_views,
        );

        let environment = GeneratedSkyboxEnvironment {
            _texture: texture,
            view: full_view,
            sampler: CubemapSamplerState::default(),
            mip_levels,
        };
        let pending = PendingGeneratedSkybox {
            environment,
            _buffers: buffers,
            _bind_groups: bind_groups,
            _texture_views: texture_views,
            _sampler: sampler,
        };
        let tx = self.jobs.submit_done_sender();
        let callback_key = request.key.clone();
        self.jobs.insert(
            request.key.clone(),
            SubmittedGpuJob {
                resources: GpuJobResources::new(),
            },
        );
        self.pending.insert(request.key, pending);
        gpu.submit_frame_batch_with_callbacks(
            vec![encoder.finish()],
            None,
            None,
            vec![Box::new(move || {
                let _ = tx.send(callback_key);
            })],
        );
        Ok(())
    }
}

/// Resolves the active skybox material into a generated cubemap request.
fn resolve_active_bake_request(
    scene: &SceneCoordinator,
    materials: &crate::backend::MaterialSystem,
    limits: &GpuLimits,
) -> Option<SkyboxBakeRequest> {
    let material_asset_id = scene.active_main_space()?.skybox_material_asset_id;
    if material_asset_id < 0 {
        return None;
    }
    let store = materials.material_property_store();
    let shader_asset_id = store.shader_asset_for_material(material_asset_id)?;
    let route_name = shader_route_name(materials, shader_asset_id)?;
    let route_lower = route_name.to_ascii_lowercase();
    let lookup = MaterialPropertyLookupIds {
        material_asset_id,
        mesh_property_block_slot0: None,
    };
    let face_size = generated_face_size(limits);
    let mut params = if route_lower.contains("gradient") {
        gradient_sky_params(store, materials.property_id_registry(), lookup)
    } else if route_lower.contains("procedural") {
        procedural_sky_params(store, materials.property_id_registry(), lookup)
    } else {
        return None;
    };
    params = params.with_sample_size(face_size);
    Some(SkyboxBakeRequest {
        key: GeneratedSkyboxKey {
            material_asset_id,
            material_generation: store.material_generation(material_asset_id),
            route_hash: hash_route_name(&route_name),
            face_size,
        },
        params,
    })
}

/// Returns a shader route name or stem for a shader asset id.
fn shader_route_name(
    materials: &crate::backend::MaterialSystem,
    shader_asset_id: i32,
) -> Option<String> {
    let registry = materials.material_registry()?;
    registry
        .stem_for_shader_asset(shader_asset_id)
        .map(str::to_string)
}

/// Hashes a route name into a stable generated-cubemap discriminator.
fn hash_route_name(route: &str) -> u64 {
    let mut hasher = DefaultHasher::new();
    route.hash(&mut hasher);
    hasher.finish()
}

/// Clamps the configured generated face size to portable device limits.
fn generated_face_size(limits: &GpuLimits) -> u32 {
    DEFAULT_GENERATED_SKYBOX_FACE_SIZE
        .min(limits.max_texture_dimension_2d())
        .max(1)
}

/// Returns the full mip count for a power-of-two or non-power-of-two texture edge.
fn mip_levels_for_edge(edge: u32) -> u32 {
    u32::BITS - edge.max(1).leading_zeros()
}

/// Returns dispatch group count for one 8x8 compute dimension.
fn dispatch_groups(size: u32) -> u32 {
    size.max(1).div_ceil(SKYBOX_WORKGROUP_EDGE)
}

/// Ensures a compute pipeline exists for an embedded shader target.
fn ensure_pipeline<'a>(
    slot: &'a mut Option<ComputePipelineWithLayout>,
    device: &wgpu::Device,
    stem: &'static str,
    entries: &[wgpu::BindGroupLayoutEntry],
) -> Result<&'a ComputePipelineWithLayout, SkyboxEnvironmentBakeError> {
    if slot.is_none() {
        let source = embedded_shaders::embedded_target_wgsl(stem)
            .ok_or(SkyboxEnvironmentBakeError::MissingShader(stem))?;
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some(stem),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(source)),
        });
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some(&format!("{stem} bind group layout")),
            entries,
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some(&format!("{stem} pipeline layout")),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some(stem),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some("main"),
            compilation_options: wgpu::PipelineCompilationOptions::default(),
            cache: None,
        });
        *slot = Some(ComputePipelineWithLayout { pipeline, layout });
    }
    slot.as_ref()
        .ok_or(SkyboxEnvironmentBakeError::MissingShader(stem))
}

/// Bind-group layout entries for the analytic skybox bake shader.
fn bake_layout_entries() -> [wgpu::BindGroupLayoutEntry; 2] {
    [
        wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        },
        storage_texture_layout_entry(1),
    ]
}

/// Bind-group layout entries for the generated cubemap downsample shader.
fn downsample_layout_entries() -> [wgpu::BindGroupLayoutEntry; 4] {
    [
        wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        },
        wgpu::BindGroupLayoutEntry {
            binding: 1,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Texture {
                sample_type: wgpu::TextureSampleType::Float { filterable: true },
                view_dimension: wgpu::TextureViewDimension::Cube,
                multisampled: false,
            },
            count: None,
        },
        wgpu::BindGroupLayoutEntry {
            binding: 2,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
            count: None,
        },
        storage_texture_layout_entry(3),
    ]
}

/// Storage texture layout entry for a single 2D-array cubemap mip.
fn storage_texture_layout_entry(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::StorageTexture {
            access: wgpu::StorageTextureAccess::WriteOnly,
            format: GENERATED_SKYBOX_FORMAT,
            view_dimension: wgpu::TextureViewDimension::D2Array,
        },
        count: None,
    }
}

/// Creates a storage view for one cubemap mip.
fn create_mip_storage_view(texture: &wgpu::Texture, mip: u32) -> wgpu::TextureView {
    texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("generated_skybox_mip_storage_view"),
        format: Some(GENERATED_SKYBOX_FORMAT),
        dimension: Some(wgpu::TextureViewDimension::D2Array),
        usage: Some(wgpu::TextureUsages::STORAGE_BINDING),
        aspect: wgpu::TextureAspect::All,
        base_mip_level: mip,
        mip_level_count: Some(1),
        base_array_layer: 0,
        array_layer_count: Some(6),
    })
}

/// Creates a cube sample view for one cubemap mip.
fn create_mip_sample_view(texture: &wgpu::Texture, mip: u32) -> wgpu::TextureView {
    texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("generated_skybox_mip_sample_view"),
        format: Some(GENERATED_SKYBOX_FORMAT),
        dimension: Some(wgpu::TextureViewDimension::Cube),
        usage: Some(wgpu::TextureUsages::TEXTURE_BINDING),
        aspect: wgpu::TextureAspect::All,
        base_mip_level: mip,
        mip_level_count: Some(1),
        base_array_layer: 0,
        array_layer_count: Some(6),
    })
}

/// Encodes compute mip generation for all generated cubemap mips after mip zero.
fn encode_downsample_mips(
    device: &wgpu::Device,
    encoder: &mut wgpu::CommandEncoder,
    pipeline: &ComputePipelineWithLayout,
    texture: &wgpu::Texture,
    sampler: &wgpu::Sampler,
    mip_levels: u32,
    buffers: &mut Vec<wgpu::Buffer>,
    bind_groups: &mut Vec<wgpu::BindGroup>,
    texture_views: &mut Vec<wgpu::TextureView>,
) {
    for mip in 1..mip_levels {
        let dst_size = mip_extent(texture.size().width, mip);
        let params = DownsampleParams {
            dst_size,
            _pad0: 0,
            _pad1: 0,
            _pad2: 0,
        };
        let params_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("generated skybox mip params"),
            contents: bytemuck::bytes_of(&params),
            usage: wgpu::BufferUsages::UNIFORM,
        });
        let source_view = create_mip_sample_view(texture, mip - 1);
        let dst_view = create_mip_storage_view(texture, mip);
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("generated skybox mip bind group"),
            layout: &pipeline.layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: params_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::TextureView(&source_view),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Sampler(sampler),
                },
                wgpu::BindGroupEntry {
                    binding: 3,
                    resource: wgpu::BindingResource::TextureView(&dst_view),
                },
            ],
        });
        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("generated skybox mip downsample"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&pipeline.pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.dispatch_workgroups(dispatch_groups(dst_size), dispatch_groups(dst_size), 6);
        }
        buffers.push(params_buffer);
        bind_groups.push(bind_group);
        texture_views.push(source_view);
        texture_views.push(dst_view);
    }
}

/// Returns a texture mip edge clamped to one texel.
fn mip_extent(base: u32, mip: u32) -> u32 {
    (base >> mip).max(1)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies mip count includes mip zero through the one-texel mip.
    #[test]
    fn mip_levels_for_edge_includes_tail_mip() {
        assert_eq!(mip_levels_for_edge(1), 1);
        assert_eq!(mip_levels_for_edge(2), 2);
        assert_eq!(mip_levels_for_edge(128), 8);
    }

    /// Verifies generated source hashes include material and face-size identity.
    #[test]
    fn generated_key_hash_changes_with_face_size() {
        let a = GeneratedSkyboxKey {
            material_asset_id: 1,
            material_generation: 2,
            route_hash: 3,
            face_size: 128,
        };
        let b = GeneratedSkyboxKey {
            face_size: 64,
            ..a.clone()
        };
        assert_ne!(a.source_hash(), b.source_hash());
    }
}
